# -*- coding: utf-8 -*-
"""Continental Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfWgzhtcCM2i9Z0ihCLu16f2qND1Bw6M
"""

from google.colab import files
uploaded = files.upload()

!pip install reverse_geocoder
import reverse_geocoder as rg

import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

df = pd.read_csv("openaq 2.csv", sep=';')
print("\nRAW HEAD:")
print(df.head())

if 'Latitude' not in df.columns or 'Longitude' not in df.columns:
    df[['Latitude_str', 'Longitude_str']] = df['Coordinates'].str.split(',', expand=True)
    df['Latitude'] = pd.to_numeric(df['Latitude_str'].str.strip(), errors='coerce')
    df['Longitude'] = pd.to_numeric(df['Longitude_str'].str.strip(), errors='coerce')
    df.drop(columns=['Latitude_str', 'Longitude_str'], inplace=True)

# Keep only necessary columns
df = df[['Country Label', 'Pollutant', 'Value', 'Latitude', 'Longitude']]
print("\nAFTER BASIC CLEAN:")
print(df.head())

def fill_missing_coordinates(df):
    # Country-level median fill
    df['Latitude'] = df.groupby('Country Label')['Latitude'].transform(
        lambda x: x.fillna(x.median())
    )
    df['Longitude'] = df.groupby('Country Label')['Longitude'].transform(
        lambda x: x.fillna(x.median())
    )

    # Continent-level median fill
    if 'Continent' in df.columns:
        df['Latitude'] = df.groupby('Continent')['Latitude'].transform(
            lambda x: x.fillna(x.median())
        )
        df['Longitude'] = df.groupby('Continent')['Longitude'].transform(
            lambda x: x.fillna(x.median())
        )

    # Global median fill
    df['Latitude'].fillna(df['Latitude'].median(), inplace=True)
    df['Longitude'].fillna(df['Longitude'].median(), inplace=True)

    return df



df = fill_missing_coordinates(df)

# Mapping table (ISO → continent)
country_to_continent = {
    'AF':'Asia','AX':'Europe','AL':'Europe','DZ':'Africa','AS':'Oceania','AD':'Europe','AO':'Africa',
    'AI':'North America','AQ':'Antarctica','AG':'North America','AR':'South America','AM':'Asia',
    'AW':'North America','AU':'Oceania','AT':'Europe','AZ':'Asia','BS':'North America','BH':'Asia',
    'BD':'Asia','BB':'North America','BY':'Europe','BE':'Europe','BZ':'North America','BJ':'Africa',
    'BM':'North America','BT':'Asia','BO':'South America','BQ':'North America','BA':'Europe',
    'BW':'Africa','BV':'Antarctica','BR':'South America','IO':'Asia','BN':'Asia','BG':'Europe',
    'BF':'Africa','BI':'Africa','KH':'Asia','CM':'Africa','CA':'North America','CV':'Africa',
    'KY':'North America','CF':'Africa','TD':'Africa','CL':'South America','CN':'Asia','CX':'Asia',
    'CC':'Asia','CO':'South America','KM':'Africa','CG':'Africa','CD':'Africa','CK':'Oceania',
    'CR':'North America','CI':'Africa','HR':'Europe','CU':'North America','CW':'North America',
    'CY':'Asia','CZ':'Europe','DK':'Europe','DJ':'Africa','DM':'North America','DO':'North America',
    'EC':'South America','EG':'Africa','SV':'North America','GQ':'Africa','ER':'Africa','EE':'Europe',
    'SZ':'Africa','ET':'Africa','FK':'South America','FO':'Europe','FJ':'Oceania','FI':'Europe',
    'FR':'Europe','GF':'South America','PF':'Oceania','TF':'Antarctica','GA':'Africa','GM':'Africa',
    'GE':'Asia','DE':'Europe','GH':'Africa','GI':'Europe','GR':'Europe','GL':'North America',
    'GD':'North America','GP':'North America','GU':'Oceania','GT':'North America','GG':'Europe',
    'GN':'Africa','GW':'Africa','GY':'South America','HT':'North America','HM':'Antarctica',
    'VA':'Europe','HN':'North America','HK':'Asia','HU':'Europe','IS':'Europe','IN':'Asia',
    'ID':'Asia','IR':'Asia','IQ':'Asia','IE':'Europe','IM':'Europe','IL':'Asia','IT':'Europe',
    'JM':'North America','JP':'Asia','JE':'Europe','JO':'Asia','KZ':'Asia','KE':'Africa',
    'KI':'Oceania','KP':'Asia','KR':'Asia','KW':'Asia','KG':'Asia','LA':'Asia','LV':'Europe',
    'LB':'Asia','LS':'Africa','LR':'Africa','LY':'Africa','LI':'Europe','LT':'Europe','LU':'Europe',
    'MO':'Asia','MK':'Europe','MG':'Africa','MW':'Africa','MY':'Asia','MV':'Asia','ML':'Africa',
    'MT':'Europe','MH':'Oceania','MQ':'North America','MR':'Africa','MU':'Africa','YT':'Africa',
    'MX':'North America','FM':'Oceania','MD':'Europe','MC':'Europe','MN':'Asia','ME':'Europe',
    'MS':'North America','MA':'Africa','MZ':'Africa','MM':'Asia','NA':'Africa','NR':'Oceania',
    'NP':'Asia','NL':'Europe','NC':'Oceania','NZ':'Oceania','NI':'North America','NE':'Africa',
    'NG':'Africa','NU':'Oceania','NF':'Oceania','MP':'Oceania','NO':'Europe','OM':'Asia',
    'PK':'Asia','PW':'Oceania','PS':'Asia','PA':'North America','PG':'Oceania','PY':'South America',
    'PE':'South America','PH':'Asia','PN':'Oceania','PL':'Europe','PT':'Europe','PR':'North America',
    'QA':'Asia','RE':'Africa','RO':'Europe','RU':'Europe','RW':'Africa','BL':'North America',
    'SH':'Africa','KN':'North America','LC':'North America','MF':'North America','PM':'North America',
    'VC':'North America','WS':'Oceania','SM':'Europe','ST':'Africa','SA':'Asia','SN':'Africa',
    'RS':'Europe','SC':'Africa','SL':'Africa','SG':'Asia','SX':'North America','SK':'Europe',
    'SI':'Europe','SB':'Oceania','SO':'Africa','ZA':'Africa','GS':'Antarctica','SS':'Africa',
    'ES':'Europe','LK':'Asia','SD':'Africa','SR':'South America','SJ':'Europe','SE':'Europe',
    'CH':'Europe','SY':'Asia','TW':'Asia','TJ':'Asia','TZ':'Africa','TH':'Asia','TL':'Asia',
    'TG':'Africa','TK':'Oceania','TO':'Oceania','TT':'North America','TN':'Africa','TR':'Asia',
    'TM':'Asia','TC':'North America','TV':'Oceania','UG':'Africa','UA':'Europe','AE':'Asia',
    'GB':'Europe','US':'North America','UM':'Oceania','UY':'South America','UZ':'Asia',
    'VU':'Oceania','VE':'South America','VN':'Asia','VG':'North America','VI':'North America',
    'WF':'Oceania','EH':'Africa','YE':'Asia','ZM':'Africa','ZW':'Africa'
}

# 1. Get unique coordinate pairs
unique_coords = df[['Latitude', 'Longitude']].drop_duplicates()

# 2. Reverse geocode ONLY the unique coordinates
def fast_get_continent(df_unique):
    coords_list = list(zip(df_unique['Latitude'], df_unique['Longitude']))
    results = rg.search(coords_list)             # fast batch lookup
    continents = []

    for res in results:
        cc = res['cc']
        continents.append(country_to_continent.get(cc, "Unknown"))

    df_unique['Continent'] = continents
    return df_unique

unique_coords = fast_get_continent(unique_coords)

# 3. Merge back to original df (VERY FAST)
df = df.merge(unique_coords, on=['Latitude', 'Longitude'], how='left')

# 4. Filter valid continents
valid_continents = ['Africa','Asia','Europe','North America','South America','Oceania','Antarctica']
df = df[df['Continent'].isin(valid_continents)]

df['Value'] = df['Value'].clip(lower=0)

print(df.isnull().sum())

pollutants_distinct = df['Pollutant'].unique()
print(pollutants_distinct)

df.head()

df.describe(include='all')

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))
plt.hist(df['Value'], bins=50)
plt.yscale('log')
plt.title("Distribution of Pollution Values (Log Scale)")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Visualization 3: Pollutant frequency count
pollutant_counts = df['Pollutant'].value_counts()

plt.figure(figsize=(8,5))
pollutant_counts.plot(kind='bar')
plt.title("Frequency of Pollutants in Dataset")
plt.xlabel("Pollutant Type")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

continent_group = df.groupby(["Continent", "Pollutant"])["Value"].mean().unstack().fillna(0)
print(continent_group)

import seaborn as sns
from matplotlib.colors import LogNorm
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.heatmap(continent_group, annot=True, cmap="magma", norm=LogNorm())
plt.title("Average Pollutant Levels by Continent")
plt.show()

"""**Interpretation of the Heatmap:**

🌍 Asia

Extremely high BC (black carbon) and CO → tied to massive industrialization + traffic.

High PM2.5/PM10 shows strong particulate pollution.
➡ Asia is the most polluted continent overall.

🇪🇺 Europe

Very elevated SO₂ → comes from coal-based power generation.

Moderate PM2.5/PM10.

🌍 Africa

Higher CO → open burning, charcoal production, agricultural fires.

🌎 North America

Lowest pollutant levels → strong regulations & cleaner technologies.

🏝 Oceania

Cleanest overall values.

🌎 South America

Moderate levels

PM10 slightly elevated (dust, urban emissions)
"""

for col in pollutants_distinct:
    plt.figure(figsize=(10,4))
    continent_group[col].plot(kind='bar')
    plt.title(f"{col} Levels by Continent")
    plt.ylabel("Concentration")
    plt.show()

corr_matrix = continent_group.corr()
print(corr_matrix)

plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True, fmt=".3f", cmap="coolwarm", linewidths=0.5)
plt.title("Correlation Between Pollutants Across Continents")
plt.show()

"""**Very high positive correlations (0.8–0.99)**
---
SO₂ ↔ NO₂ (0.993)

Strong indicator of industrial + vehicle combustion occurring in the same regions.

PM2.5 ↔ PM10 (0.991)

Expected because both are particulate matter:

PM10 = coarse dust

PM2.5 = fine particles

These pollutants often rise and fall together.

NO ↔ NO₂ (0.866)

Both are nitrogen oxides and share similar emission sources:

Traffic

Industrial combustion

**Medium positive correlations (0.5–0.8)**
---
CO ↔ O3 (0.788)

CO emissions often come from incomplete combustion

Ozone formation is linked to NOx + hydrocarbons → related chemistry

BC ↔ PM1 / PM10 / PM2.5 (0.78, -0.52, -0.55)

BC correlates strongly with PM1 (fine particles), but negatively with PM10.
This is true because:

PM10 includes dust + soil particles → unrelated to BC

PM1 includes combustion particles → directly related to BC

**Negative correlations**
---
BC ↔ PM10 (-0.529)

Means:

Areas with high black carbon (industrial, traffic-heavy)

Do not necessarily have high coarse dust (PM10)
"""

plt.figure(figsize=(10,6))
sns.boxplot(data=df, x="Pollutant", y="Value", palette="viridis")
plt.yscale("log")
plt.title("Boxplot of Pollutants (Log Scale)")
plt.tight_layout()
plt.show()

df.to_csv('openaq_cleaned.csv', index=False)
files.download('openaq_cleaned.csv')

for p in pollutants_distinct:
    subset = df[df["Pollutant"] == p]["Value"]
    if len(subset) > 0:
        plt.figure(figsize=(7,4))
        plt.hist(subset, bins=40)
        plt.yscale("log")
        plt.title(f"Distribution of {p}")
        plt.xlabel("Value")
        plt.ylabel("Frequency (log scale)")
        plt.tight_layout()
        plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

# Define pivot DataFrame (assuming df and pollutants_distinct are defined)
pivot = df.pivot_table(
    index=["Latitude", "Longitude"],
    columns="Pollutant",
    values="Value",
    aggfunc="mean"
).fillna(0) # Changed .dropna() to .fillna(0) to prevent empty DataFrame

pivot = pivot[[col for col in pivot.columns if col in pollutants_distinct]]

cluster_df = pivot.copy()

scaler = StandardScaler()
scaled = scaler.fit_transform(cluster_df)

kmeans = KMeans(n_clusters=4, random_state=42, n_init='auto')
cluster_df["Cluster"] = kmeans.fit_predict(scaled)

plt.figure(figsize=(7,6))
sns.scatterplot(
    data=cluster_df,
    x="PM2.5", y="PM10",
    hue="Cluster",
    palette="tab10",
    s=40
)
plt.xscale("log"); plt.yscale("log")
plt.title("K-Means Clusters (PM2.5 vs PM10)")
plt.tight_layout()
plt.show()

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pc = pca.fit_transform(scaled)

cluster_df["PC1"] = pc[:,0]
cluster_df["PC2"] = pc[:,1]

plt.figure(figsize=(8,6))
sns.scatterplot(
    data=cluster_df, x="PC1", y="PC2",
    hue="Cluster", palette="tab10", s=50
)
plt.title("PCA of Pollution Dataset (2 Components)")
plt.tight_layout()
plt.show()

print("PCA Explained Variance:", pca.explained_variance_ratio_)

import folium
from folium.plugins import MarkerCluster

df_sample = df.sample(n=1000, random_state=42) # Taking a sample for better map rendering

cluster_map = folium.Map(location=[20,0], zoom_start=2)
marker_cluster = MarkerCluster().add_to(cluster_map)

for _, row in df_sample.iterrows():
    folium.Marker(
        location=[row["Latitude"], row["Longitude"]],
        tooltip=f"{row['Pollutant']} = {row['Value']} ({row['Country Label']})"
    ).add_to(marker_cluster)

cluster_map.save("cluster_pollution_map.html")
print("Saved: cluster_pollution_map.html")